pipeline {
    agent any
    stages {
        stage('Compile Stage') {
            steps {
                git 'https://github.com/bugfreeautomation/bugfree-automation/'
                dir('authframeworkAndroid') {
                    withMaven(maven : 'maven-3.3.9') {
                        sh 'mvn clean compile'
                    }
                
                }
            }
        }
             stage('Testing Stage') {
            steps {
                git 'https://github.com/bugfreeautomation/bugfree-automation/'
                dir('authframeworkAndroid') {
                    withMaven(maven : 'maven-3.3.9') {
                        sh 'mvn test -Dcucumber.options="--tags @SSNMissing"'
                    }
                    cucumber fileIncludePattern: 'results/*.json', sortingMethod: 'ALPHABETICAL'
                }
            }
        }
    }
}

